-- FreshTrack DDL
-- Oracle-friendly table structure for the database lab project.

CREATE TABLE categories (
	category_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	category_name VARCHAR2(100) NOT NULL,
	description VARCHAR2(255),
	CONSTRAINT pk_categories PRIMARY KEY (category_id),
	CONSTRAINT uq_categories_name UNIQUE (category_name)
);

CREATE TABLE suppliers (
	supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	supplier_name VARCHAR2(120) NOT NULL,
	contact_person VARCHAR2(100),
	phone VARCHAR2(20),
	email VARCHAR2(120),
	address VARCHAR2(255),
	CONSTRAINT pk_suppliers PRIMARY KEY (supplier_id),
	CONSTRAINT uq_suppliers_email UNIQUE (email)
);

CREATE TABLE users (
	user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	full_name VARCHAR2(120) NOT NULL,
	email VARCHAR2(120) NOT NULL,
	phone VARCHAR2(20),
	role VARCHAR2(20) DEFAULT 'STAFF' NOT NULL,
	created_at DATE DEFAULT SYSDATE NOT NULL,
	CONSTRAINT pk_users PRIMARY KEY (user_id),
	CONSTRAINT uq_users_email UNIQUE (email),
	CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'MANAGER', 'STAFF'))
);

CREATE TABLE products (
	product_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	category_id NUMBER NOT NULL,
	product_name VARCHAR2(120) NOT NULL,
	brand VARCHAR2(100),
	unit_of_measure VARCHAR2(30) NOT NULL,
	shelf_life_days NUMBER(5) NOT NULL,
	reorder_level NUMBER(10) DEFAULT 0 NOT NULL,
	status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
	CONSTRAINT pk_products PRIMARY KEY (product_id),
	CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (category_id),
	CONSTRAINT uq_products_name UNIQUE (category_id, product_name),
	CONSTRAINT ck_products_shelf_life CHECK (shelf_life_days > 0),
	CONSTRAINT ck_products_reorder_level CHECK (reorder_level >= 0),
	CONSTRAINT ck_products_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE purchases (
	purchase_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	supplier_id NUMBER NOT NULL,
	purchased_by NUMBER NOT NULL,
	purchase_date DATE DEFAULT SYSDATE NOT NULL,
	invoice_no VARCHAR2(50),
	total_amount NUMBER(12, 2) DEFAULT 0 NOT NULL,
	status VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL,
	CONSTRAINT pk_purchases PRIMARY KEY (purchase_id),
	CONSTRAINT fk_purchases_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id),
	CONSTRAINT fk_purchases_user FOREIGN KEY (purchased_by) REFERENCES users (user_id),
	CONSTRAINT uq_purchases_invoice UNIQUE (invoice_no),
	CONSTRAINT ck_purchases_total CHECK (total_amount >= 0),
	CONSTRAINT ck_purchases_status CHECK (status IN ('COMPLETED', 'PENDING', 'CANCELLED'))
);

CREATE TABLE batches (
	batch_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	purchase_id NUMBER NOT NULL,
	product_id NUMBER NOT NULL,
	batch_code VARCHAR2(50) NOT NULL,
	manufacture_date DATE,
	expiry_date DATE NOT NULL,
	quantity_received NUMBER(10) NOT NULL,
	quantity_available NUMBER(10) NOT NULL,
	unit_cost NUMBER(12, 2) NOT NULL,
	storage_location VARCHAR2(100),
	batch_status VARCHAR2(20) DEFAULT 'IN_STOCK' NOT NULL,
	CONSTRAINT pk_batches PRIMARY KEY (batch_id),
	CONSTRAINT fk_batches_purchase FOREIGN KEY (purchase_id) REFERENCES purchases (purchase_id),
	CONSTRAINT fk_batches_product FOREIGN KEY (product_id) REFERENCES products (product_id),
	CONSTRAINT uq_batches_code UNIQUE (batch_code),
	CONSTRAINT ck_batches_quantity_received CHECK (quantity_received > 0),
	CONSTRAINT ck_batches_quantity_available CHECK (quantity_available >= 0),
	CONSTRAINT ck_batches_unit_cost CHECK (unit_cost >= 0),
	CONSTRAINT ck_batches_status CHECK (batch_status IN ('IN_STOCK', 'LOW_STOCK', 'EXPIRED', 'DONATED', 'WASTED'))
);

CREATE TABLE inventory_movements (
	movement_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	batch_id NUMBER NOT NULL,
	user_id NUMBER NOT NULL,
	movement_type VARCHAR2(20) NOT NULL,
	movement_date DATE DEFAULT SYSDATE NOT NULL,
	quantity NUMBER(10) NOT NULL,
	reference_type VARCHAR2(30),
	reference_id NUMBER,
	notes VARCHAR2(255),
	CONSTRAINT pk_inventory_movements PRIMARY KEY (movement_id),
	CONSTRAINT fk_movements_batch FOREIGN KEY (batch_id) REFERENCES batches (batch_id),
	CONSTRAINT fk_movements_user FOREIGN KEY (user_id) REFERENCES users (user_id),
	CONSTRAINT ck_movements_type CHECK (movement_type IN ('IN', 'OUT', 'ADJUST', 'DONATE', 'WASTE')),
	CONSTRAINT ck_movements_quantity CHECK (quantity > 0)
);

CREATE TABLE donations (
	donation_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	batch_id NUMBER NOT NULL,
	approved_by NUMBER NOT NULL,
	donation_date DATE DEFAULT SYSDATE NOT NULL,
	organization_name VARCHAR2(150) NOT NULL,
	quantity_donated NUMBER(10) NOT NULL,
	status VARCHAR2(20) DEFAULT 'APPROVED' NOT NULL,
	CONSTRAINT pk_donations PRIMARY KEY (donation_id),
	CONSTRAINT fk_donations_batch FOREIGN KEY (batch_id) REFERENCES batches (batch_id),
	CONSTRAINT fk_donations_user FOREIGN KEY (approved_by) REFERENCES users (user_id),
	CONSTRAINT ck_donations_quantity CHECK (quantity_donated > 0),
	CONSTRAINT ck_donations_status CHECK (status IN ('APPROVED', 'PENDING', 'REJECTED'))
);

CREATE TABLE waste_records (
	waste_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	batch_id NUMBER NOT NULL,
	recorded_by NUMBER NOT NULL,
	waste_date DATE DEFAULT SYSDATE NOT NULL,
	quantity_wasted NUMBER(10) NOT NULL,
	reason VARCHAR2(255) NOT NULL,
	CONSTRAINT pk_waste_records PRIMARY KEY (waste_id),
	CONSTRAINT fk_waste_batch FOREIGN KEY (batch_id) REFERENCES batches (batch_id),
	CONSTRAINT fk_waste_user FOREIGN KEY (recorded_by) REFERENCES users (user_id),
	CONSTRAINT ck_waste_quantity CHECK (quantity_wasted > 0)
);

CREATE TABLE alerts (
	alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	batch_id NUMBER NOT NULL,
	alert_type VARCHAR2(30) NOT NULL,
	alert_date DATE DEFAULT SYSDATE NOT NULL,
	status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
	message VARCHAR2(255) NOT NULL,
	CONSTRAINT pk_alerts PRIMARY KEY (alert_id),
	CONSTRAINT fk_alerts_batch FOREIGN KEY (batch_id) REFERENCES batches (batch_id),
	CONSTRAINT ck_alerts_type CHECK (alert_type IN ('EXPIRY', 'LOW_STOCK', 'DONATION', 'WASTE')),
	CONSTRAINT ck_alerts_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'CLOSED'))
);

